Updated run_app Jenkinsfile and Packer Template

diff --git a/run_app/Jenkinsfile b/run_app/Jenkinsfile
--- a/run_app/Jenkinsfile
+++ b/run_app/Jenkinsfile
@@ -1,23 +1,27 @@
 pipeline {
     agent any
 
+    environment {
+        DOCKERHUB_REPOSITORY = credentials('dockerhub-repository')
+    }
+
     stages {
         stage ('Pull Docker Image') {
             steps {
-		sh 'docker pull yhaeffner/congratulations_app:dev'
+		        sh 'docker pull "$DOCKERHUB_REPOSITORY":prod'
             }
         }
         
         stage ('Run or Start Container') {
             steps {
             	sh '''
-			if ! docker container ls -a | grep -Fq congratulationsApp 1>/dev/null; then
-			  echo "# Docker congratulationsApp container could not be found, running a new one"
-			  docker run -d -p 8282:8282 --name congratulationsApp yhaeffner/congratulations_app:dev
-			else
-			  echo "# Docker congratulationsApp container found, starting it..."
-			  docker start congratulationsApp
-			fi
+        			if ! docker container ls -a | grep -Fq congratulationsApp 1>/dev/null; then
+        			  echo "# Docker congratulationsApp container could not be found, running a new one"
+        			  docker run -d -p 8282:8282 --name congratulationsApp "$DOCKERHUB_REPOSITORY":prod
+        			else
+        			  echo "# Docker congratulationsApp container found, starting it..."
+        			  docker start congratulationsApp
+        			fi
             	'''
             }
         }
